[tool.poetry]
name = "high"
version = "0.1.0"
description = "Hy utility belt"
authors = ["Abhinav Tushar <lepisma@fastmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
hy = "0.13.0"
colorama = "^0.3.9"
matplotlib = "^2.2"
numpy = "^1.15"

[tool.poetry.dev-dependencies]
